syntax on
set relativenumber
set exrc
set belloff=all
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set nu
set nowrap
set smartcase
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
set whichwrap+=<,>,h,l,[,]
set guicursor=
set number
set nohlsearch
set signcolumn=yes
set colorcolumn=80
set scrolloff=8
set hidden
set noshowmode
set ignorecase
set completeopt=menuone,noinsert,noselect
